{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "springk8s.serviceAccountName" . }}
  labels:
{{ include "springk8s.labels" . | indent 4 }}
{{- end -}}
